baseURL = 'https://cssharsha.github.io/'
languageCode = 'en-us'
title = 'sreesmere.com'
theme = 'PaperMod'

[params]
    [params.homeInfoParams]
    Title = "Into the messy beads in sreesmere"
    Content = "I try to help robots answer where am I question. In my spare time I read a lot of SFF, brew some beer, hike mounds and run roads. I used to have one but am reopning the dump yard again for my rants after a long time. What is sreesmere you ask? Well...its cosmere but with sree. Get it? Anyways there's a link to my goodreads profile if you haven't noticed. üëæüï∏Ô∏è"
    
    [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/sreeharshacs"
    
    [[params.socialIcons]]
    name = "github" 
    url = "https://github.com/cssharsha"
    
    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sree-harsha-c-s/"
    
    [[params.socialIcons]]
    name = "goodreads" 
    url = "https://www.goodreads.com/cssharsha"

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
    
    [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"